using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NUnit.Framework;

namespace MayoSolutions.Framework.IO.Tests.Bench
{
    public class VirtualFileSystemTests
    {
        [Test]
        public void FixFolderNotReady()
        {
            var vfs = VirtualFileSystem
                .FromPhysicalPath(@"F:\")
                .AndPhysicalPath(@"F:\_TorrentCache")
                ;
        }

        [Test]
        public void FixSequenceContainsMultipleBug()
        {
            var vfs = VirtualFileSystem
                .WithPath(@"F:\")
                .AndPath(@"F:\_TorrentCache")
                .AndPath(@"F:\_TorrentCache\_Completed (local)")
                .AndPath(@"F:\_TorrentCache\_Completed (local)\TV")
                .AndPath(@"F:\_TorrentCache\_Completed (local)\TV\Archer")
                .AndPath(@"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 10")
                .WithFiles(new[]
                {
                    @"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 10\01 - 1999- Bort The Garj.mp4",
                    @"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 10\02 - 1999- Happy Borthday.mp4",
                    @"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 10\03 - 1999- The Leftovers.mp4",
                    @"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 10\04 - 1999- Dining With The Zarglorp.mp4",
                    @"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 10\05 - 1999- Mr. Deadly Goes To Town.mp4",
                    @"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 10\06 - 1999- Road Trip.mp4",
                    @"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 10\07 - 1999- Space Pirates.mp4",
                    @"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 10\08 - 1999- Cubert.mp4",
                    @"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 10\09 - 1999- Robert De Niro.mp4"
                });
        }


        [Test]
        public void FixSequenceContainsMultipleBug2()
        {
            var vfs = new VirtualFileSystem()
                .WithFiles(new[]
                {
                    @"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 10\01 - 1999- Bort The Garj.mp4",
                    @"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 10\02 - 1999- Happy Borthday.mp4",
                    @"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 10\03 - 1999- The Leftovers.mp4",
                    @"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 10\04 - 1999- Dining With The Zarglorp.mp4",
                    @"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 10\05 - 1999- Mr. Deadly Goes To Town.mp4",
                    @"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 10\06 - 1999- Road Trip.mp4",
                    @"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 10\07 - 1999- Space Pirates.mp4",
                    @"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 10\08 - 1999- Cubert.mp4",
                    @"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 10\09 - 1999- Robert De Niro.mp4"
                });
        }


        [Test]
        public void FixVolumeContainsNoDirectories()
        {
            var vfs = new VirtualFileSystem();
			#region initialize
			vfs.WithFiles(new[] {
		@"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 10\s10e01.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 10\s10e02.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 10\s10e03.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 10\s10e04.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 10\s10e05.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 10\s10e06.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 10\s10e07.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 10\s10e08.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 10\s10e09.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 11\s11e01.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 11\s11e02.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 11\s11e03.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 11\s11e04.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 11\s11e05.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 11\Subs\s11e01\2_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 11\Subs\s11e02\2_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 11\Subs\s11e03\2_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 11\Subs\s11e04\2_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 11\Subs\s11e05\2_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 9\s09e01.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 9\s09e02.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 9\s09e03.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 9\s09e04.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 9\s09e05.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 9\s09e06.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 9\s09e07.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Archer\Season 9\s09e08.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Big Mouth\Season 0\01 - My Furry Valentine.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Big Mouth\Season 2\01 - Am I Normal.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Big Mouth\Season 2\02 - What Is It About Boobs.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Big Mouth\Season 2\03 - The Shame Wizard.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Big Mouth\Season 2\04 - Steve The Virgin.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Big Mouth\Season 2\05 - The Planned Parenthood Show.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Big Mouth\Season 2\06 - Drug Buddies.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Big Mouth\Season 2\07 - Guy Town.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Big Mouth\Season 2\08 - Dark Side Of The Boob.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Big Mouth\Season 2\09 - Smooch Or Share.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Big Mouth\Season 2\10 - The Department Of Puberty.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Brockmire\Season 2\01 - The Getaway Game.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Brockmire\Season 2\02 - Platoon Player.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Brockmire\Season 2\03 - Knuckleball.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Brockmire\Season 2\04 - Retirement Ceremony.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Brockmire\Season 2\05 - Make-up Game.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Brockmire\Season 2\06 - Broadcasters Jinx.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Brockmire\Season 2\07 - Caught In A Rundown.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Brockmire\Season 2\08 - In The Cellar.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Brockmire\Season 3\01 - Clubhouse Cancer.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Brockmire\Season 3\02 - Player To Be Named Later.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Brockmire\Season 3\03 - The Yips.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Brockmire\Season 3\04 - Banned For Life.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Brockmire\Season 3\05 - Clubhouse Chemistry.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Brockmire\Season 3\06 - Placed On Waivers.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Brockmire\Season 3\07 - Disabled List.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Brockmire\Season 3\08 - Opening Day.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Good Omens\Season 1\01 - In The Beginning.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Good Omens\Season 1\02 - The Book.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Good Omens\Season 1\03 - Hard Times.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Good Omens\Season 1\04 - Saturday Morning Funtime.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Good Omens\Season 1\05 - The Doomsday Option.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Good Omens\Season 1\06 - The Very Last Day Of The Rest Of Their Lives.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Marvel's Daredevil\Season 3\01 - Resurrection.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Marvel's Daredevil\Season 3\02 - Please.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Marvel's Daredevil\Season 3\03 - No Good Deed.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Marvel's Daredevil\Season 3\04 - Blindsided.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Marvel's Daredevil\Season 3\05 - The Perfect Game.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Marvel's Daredevil\Season 3\06 - The Devil You Know.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Marvel's Daredevil\Season 3\07 - Aftermath.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Marvel's Daredevil\Season 3\08 - Upstairs Downstairs.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Marvel's Daredevil\Season 3\09 - Revelations.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Marvel's Daredevil\Season 3\10 - Karen.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Marvel's Daredevil\Season 3\11 - Reunion.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Marvel's Daredevil\Season 3\12 - One Last Shot.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Marvel's Daredevil\Season 3\13 - A New Napkin.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Marvel's Daredevil\Season 3\cover.jpg",
		@"F:\_TorrentCache\_Completed (local)\TV\Marvel's The Punisher\Season 2\01 - Roadhouse Blues.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Marvel's The Punisher\Season 2\02 - Fight Or Flight.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Marvel's The Punisher\Season 2\03 - Trouble The Water.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Marvel's The Punisher\Season 2\04 - Scar Tissue.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Marvel's The Punisher\Season 2\05 - One-Eyed Jacks.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Marvel's The Punisher\Season 2\06 - Nakazat.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Marvel's The Punisher\Season 2\07 - One Bad Day.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Marvel's The Punisher\Season 2\08 - My Brothers Keeper.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Marvel's The Punisher\Season 2\09 - Flustercluck.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Marvel's The Punisher\Season 2\10 - The Dark Hearts Of Men.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Marvel's The Punisher\Season 2\11 - The Abyss.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Marvel's The Punisher\Season 2\12 - Collision Course.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Marvel's The Punisher\Season 2\13 - The Whirlwind.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek - Lower Decks\Season 1\01 - Second Contact.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek - Lower Decks\Season 1\02 - Envoys.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek - Lower Decks\Season 1\03 - Temporal Edict.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek - Lower Decks\Season 1\04 - Moist Vessel.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek - Lower Decks\Season 1\05 - Cupid's Errant Arrow.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek - Lower Decks\Season 1\06 - Terminal Provocations.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek - Lower Decks\Season 1\07 - Much Ado About Boimler.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek - Lower Decks\Season 1\08 - Veritas.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek - Lower Decks\Season 1\09 - Crisis Point.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek - Lower Decks\Season 1\10 - No Small Parts.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek - Lower Decks\Season 1\Subs\01 - Second Contact\2_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek - Lower Decks\Season 1\Subs\01 - Second Contact\3_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek - Lower Decks\Season 1\Subs\02 - Envoys\2_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek - Lower Decks\Season 1\Subs\03 - Temporal Edict\2_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek - Lower Decks\Season 1\Subs\03 - Temporal Edict\3_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek - Lower Decks\Season 1\Subs\04 - Moist Vessel\2_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek - Lower Decks\Season 1\Subs\04 - Moist Vessel\3_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek - Lower Decks\Season 1\Subs\05 - Cupid's Errant Arrow\2_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek - Lower Decks\Season 1\Subs\05 - Cupid's Errant Arrow\3_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek - Lower Decks\Season 1\Subs\06 - Terminal Provocations\2_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek - Lower Decks\Season 1\Subs\06 - Terminal Provocations\3_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek - Lower Decks\Season 1\Subs\07 - Much Ado About Boimler\2_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek - Lower Decks\Season 1\Subs\07 - Much Ado About Boimler\3_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek - Lower Decks\Season 1\Subs\08 - Veritas\2_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek - Lower Decks\Season 1\Subs\08 - Veritas\3_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek - Lower Decks\Season 1\Subs\09 - Crisis Point\2_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek - Lower Decks\Season 1\Subs\09 - Crisis Point\3_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek - Lower Decks\Season 1\Subs\10 - No Small Parts\2_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek Discovery\Season 0\02 - Short Treks- Runaway.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek Discovery\Season 0\03 - Short Treks- Calypso.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek Discovery\Season 0\04 - Short Treks- The Brightest Star.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek Discovery\Season 0\05 - Short Treks- The Escape Artist.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek Discovery\Season 1\01 - The Vulcan Hello.avi",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek Discovery\Season 1\02 - Battle At The Binary Stars.avi",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek Discovery\Season 1\03 - Context Is For Kings.avi",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek Discovery\Season 1\04 - The Butchers Knife Cares Not For The Lambs Cry.avi",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek Discovery\Season 1\05 - Choose Your Pain.avi",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek Discovery\Season 1\06 - Lethe.avi",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek Discovery\Season 1\07 - Magic To Make The Sanest Man Go Mad.avi",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek Discovery\Season 1\08 - Si Vis Pacem, Para Bellum.avi",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek Discovery\Season 1\09 - Into The Forest I Go.avi",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek Discovery\Season 1\10 - Despite Yourself.avi",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek Discovery\Season 1\11 - The Wolf Inside.avi",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek Discovery\Season 1\12 - Vaulting Ambition.avi",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek Discovery\Season 1\13 - Whats Past Is Prologue.avi",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek Discovery\Season 1\14 - The War Without, The War Within.avi",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek Discovery\Season 1\15 - Will You Take My Hand.avi",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek Discovery\Season 2\01 - Brother.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek Discovery\Season 2\02 - New Eden.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek Discovery\Season 2\03 - Point Of Light.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek Discovery\Season 2\04 - An Obol For Charon.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek Discovery\Season 2\05 - Saints Of Imperfection.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek Discovery\Season 2\06 - The Sound Of Thunder.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek Discovery\Season 2\07 - Light And Shadows.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek Discovery\Season 2\08 - If Memory Serves.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek Discovery\Season 2\09 - Project Daedalus.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek Discovery\Season 2\10 - The Red Angel.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek Discovery\Season 2\11 - Perpetual Infinity.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek Discovery\Season 2\12 - Through The Valley Of Shadows.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek Discovery\Season 2\13 - Such Sweet Sorrow (1).mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Trek Discovery\Season 2\14 - Such Sweet Sorrow (2).mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 3\01 - Steps Into Shadow.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 3\02 - The Holocrons Of Fate.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 3\03 - The Antilles Extraction.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 3\04 - Heras Heroes.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 3\05 - The Last Battle.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 3\06 - Imperial Supercommandos.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 3\07 - Iron Squadron.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 3\08 - The Wynkahthu Job.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 3\09 - An Inside Man.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 3\10 - Visions And Voices.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 3\11 - Ghosts Of Geonosis (1).mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 3\12 - Ghosts Of Geonosis (2).mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 3\13 - Warhead.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 3\14 - Trials Of The Darksaber.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 3\15 - Legacy Of Mandalore.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 3\16 - Through Imperial Eyes.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 3\17 - Secret Cargo.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 3\18 - Double Agent Droid.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 3\19 - Twin Suns.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 3\20 - Zero Hour (Part 1).mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 3\21 - Zero Hour (Part 2).mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 4\01 - Heroes Of Mandalore (Part 1).mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 4\02 - Heroes Of Mandalore (Part 2).mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 4\03 - In The Name Of The Rebellion (1).mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 4\04 - In The Name Of The Rebellion (2).mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 4\05 - The Occupation.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 4\06 - Flight Of The Defender.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 4\07 - Kindred.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 4\08 - Crawler Commanders.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 4\09 - Rebel Assault.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 4\10 - Jedi Night.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 4\11 - DUME.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 4\12 - Wolves And A Door.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 4\13 - A World Between Worlds.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 4\14 - A Fools Hope.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Rebels\Season 4\16 - Family Reunion - And Farewell.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Resistance\Season 0\01 - Dart And Cover.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Resistance\Season 0\02 - The Search For Kaz.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Resistance\Season 0\03 - Neekus Reward.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Resistance\Season 0\04 - When Thieves Drop By.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Resistance\Season 0\05 - Treasure Chest.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Resistance\Season 0\06 - G-LN.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Resistance\Season 0\07 - Buckets Quest.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Resistance\Season 0\08 - Unmotivated.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Resistance\Season 0\09 - The Need For Speed.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Resistance\Season 0\10 - Sixty Seconds To Destruction.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Resistance\Season 0\11 - Buggles Day Out.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Resistance\Season 0\12 - The Rematch.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Resistance\Season 1\11 - Bibo.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Resistance\Season 1\12 - Dangerous Business.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Resistance\Season 1\13 - The Doza Dilemma.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Resistance\Season 1\14 - The First Order Occupation.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Resistance\Season 1\15 - The New Trooper.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Resistance\Season 1\16 - The Core Problem.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Resistance\Season 1\17 - The Disappeared.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Resistance\Season 1\18 - Descent.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Resistance\Season 1\19 - No Escape (Part 1).mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Star Wars Resistance\Season 1\20 - No Escape (Part 2).mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Tales from the Tour Bus\Season 2\08 - Betty Davis.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 1\01 - The Name Of The Game.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 1\02 - Cherry.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 1\03 - Get Some.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 1\04 - The Female Of The Species.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 1\05 - Good For The Soul.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 1\06 - The Innocents.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 1\07 - The Self-Preservation Society.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 1\08 - You Found Me.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\01 - The Big Ride.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\02 - Proper Preparation and Planning.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\03 - Over the Hill with the Swords of a Thousand Men.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\04 - Nothing Like It in the World.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\05 - We Gotta Go Now.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\06 - The Bloody Doors Off.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\07 - Butcher, Baker, Candlestick Maker.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\08 - What I Know.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\01 - The Big Ride\10_fil.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\01 - The Big Ride\11_French.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\01 - The Big Ride\12_Hebrew.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\01 - The Big Ride\13_hin.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\01 - The Big Ride\14_Indonesian.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\01 - The Big Ride\15_Italian.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\01 - The Big Ride\16_Japanese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\01 - The Big Ride\17_Korean.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\01 - The Big Ride\18_may.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\01 - The Big Ride\19_Bokmal.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\01 - The Big Ride\20_Dutch.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\01 - The Big Ride\21_Polish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\01 - The Big Ride\22_Portuguese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\01 - The Big Ride\23_Portuguese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\01 - The Big Ride\24_Russian.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\01 - The Big Ride\25_Swedish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\01 - The Big Ride\26_tam.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\01 - The Big Ride\27_tel.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\01 - The Big Ride\28_Thai.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\01 - The Big Ride\29_Turkish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\01 - The Big Ride\2_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\01 - The Big Ride\30_Chinese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\01 - The Big Ride\31_Chinese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\01 - The Big Ride\3_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\01 - The Big Ride\4_Arabic.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\01 - The Big Ride\5_Danish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\01 - The Big Ride\6_German.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\01 - The Big Ride\7_Spanish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\01 - The Big Ride\8_Spanish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\01 - The Big Ride\9_Finnish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\02 - Proper Preparation and Planning\10_fil.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\02 - Proper Preparation and Planning\11_French.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\02 - Proper Preparation and Planning\12_Hebrew.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\02 - Proper Preparation and Planning\13_hin.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\02 - Proper Preparation and Planning\14_Indonesian.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\02 - Proper Preparation and Planning\15_Italian.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\02 - Proper Preparation and Planning\16_Japanese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\02 - Proper Preparation and Planning\17_Korean.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\02 - Proper Preparation and Planning\18_may.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\02 - Proper Preparation and Planning\19_Bokmal.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\02 - Proper Preparation and Planning\20_Dutch.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\02 - Proper Preparation and Planning\21_Polish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\02 - Proper Preparation and Planning\22_Portuguese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\02 - Proper Preparation and Planning\23_Portuguese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\02 - Proper Preparation and Planning\24_Russian.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\02 - Proper Preparation and Planning\25_Swedish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\02 - Proper Preparation and Planning\26_tam.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\02 - Proper Preparation and Planning\27_tel.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\02 - Proper Preparation and Planning\28_Thai.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\02 - Proper Preparation and Planning\29_Turkish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\02 - Proper Preparation and Planning\2_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\02 - Proper Preparation and Planning\30_Chinese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\02 - Proper Preparation and Planning\31_Chinese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\02 - Proper Preparation and Planning\3_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\02 - Proper Preparation and Planning\4_Arabic.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\02 - Proper Preparation and Planning\5_Danish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\02 - Proper Preparation and Planning\6_German.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\02 - Proper Preparation and Planning\7_Spanish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\02 - Proper Preparation and Planning\8_Spanish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\02 - Proper Preparation and Planning\9_Finnish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\03 - Over the Hill with the Swords of a Thousand Men\10_fil.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\03 - Over the Hill with the Swords of a Thousand Men\11_French.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\03 - Over the Hill with the Swords of a Thousand Men\12_Hebrew.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\03 - Over the Hill with the Swords of a Thousand Men\13_hin.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\03 - Over the Hill with the Swords of a Thousand Men\14_Indonesian.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\03 - Over the Hill with the Swords of a Thousand Men\15_Italian.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\03 - Over the Hill with the Swords of a Thousand Men\16_Japanese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\03 - Over the Hill with the Swords of a Thousand Men\17_Korean.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\03 - Over the Hill with the Swords of a Thousand Men\18_may.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\03 - Over the Hill with the Swords of a Thousand Men\19_Bokmal.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\03 - Over the Hill with the Swords of a Thousand Men\20_Dutch.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\03 - Over the Hill with the Swords of a Thousand Men\21_Polish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\03 - Over the Hill with the Swords of a Thousand Men\22_Portuguese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\03 - Over the Hill with the Swords of a Thousand Men\23_Portuguese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\03 - Over the Hill with the Swords of a Thousand Men\24_Russian.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\03 - Over the Hill with the Swords of a Thousand Men\25_Swedish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\03 - Over the Hill with the Swords of a Thousand Men\26_tam.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\03 - Over the Hill with the Swords of a Thousand Men\27_tel.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\03 - Over the Hill with the Swords of a Thousand Men\28_Thai.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\03 - Over the Hill with the Swords of a Thousand Men\29_Turkish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\03 - Over the Hill with the Swords of a Thousand Men\2_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\03 - Over the Hill with the Swords of a Thousand Men\30_Chinese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\03 - Over the Hill with the Swords of a Thousand Men\31_Chinese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\03 - Over the Hill with the Swords of a Thousand Men\3_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\03 - Over the Hill with the Swords of a Thousand Men\4_Arabic.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\03 - Over the Hill with the Swords of a Thousand Men\5_Danish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\03 - Over the Hill with the Swords of a Thousand Men\6_German.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\03 - Over the Hill with the Swords of a Thousand Men\7_Spanish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\03 - Over the Hill with the Swords of a Thousand Men\8_Spanish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\03 - Over the Hill with the Swords of a Thousand Men\9_Finnish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\04 - Nothing Like It in the World\10_Indonesian.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\04 - Nothing Like It in the World\11_Italian.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\04 - Nothing Like It in the World\12_Dutch.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\04 - Nothing Like It in the World\13_nor.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\04 - Nothing Like It in the World\14_Polish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\04 - Nothing Like It in the World\15_Portuguese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\04 - Nothing Like It in the World\16_Portuguese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\04 - Nothing Like It in the World\17_Finnish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\04 - Nothing Like It in the World\18_Swedish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\04 - Nothing Like It in the World\19_Und.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\04 - Nothing Like It in the World\20_Turkish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\04 - Nothing Like It in the World\21_Russian.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\04 - Nothing Like It in the World\22_Hebrew.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\04 - Nothing Like It in the World\23_Arabic.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\04 - Nothing Like It in the World\24_hin.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\04 - Nothing Like It in the World\25_tam.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\04 - Nothing Like It in the World\26_tel.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\04 - Nothing Like It in the World\27_Thai.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\04 - Nothing Like It in the World\28_Chinese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\04 - Nothing Like It in the World\29_Chinese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\04 - Nothing Like It in the World\2_Und.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\04 - Nothing Like It in the World\30_Japanese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\04 - Nothing Like It in the World\31_Korean.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\04 - Nothing Like It in the World\3_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\04 - Nothing Like It in the World\4_may.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\04 - Nothing Like It in the World\5_Danish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\04 - Nothing Like It in the World\6_German.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\04 - Nothing Like It in the World\7_Spanish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\04 - Nothing Like It in the World\8_Spanish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\04 - Nothing Like It in the World\9_French.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\05 - We Gotta Go Now\10_French.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\05 - We Gotta Go Now\11_Indonesian.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\05 - We Gotta Go Now\12_Italian.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\05 - We Gotta Go Now\13_Dutch.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\05 - We Gotta Go Now\14_nor.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\05 - We Gotta Go Now\15_Polish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\05 - We Gotta Go Now\16_Portuguese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\05 - We Gotta Go Now\17_Portuguese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\05 - We Gotta Go Now\18_Finnish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\05 - We Gotta Go Now\19_Swedish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\05 - We Gotta Go Now\20_Turkish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\05 - We Gotta Go Now\21_Russian.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\05 - We Gotta Go Now\22_Hebrew.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\05 - We Gotta Go Now\23_Arabic.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\05 - We Gotta Go Now\24_hin.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\05 - We Gotta Go Now\25_tam.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\05 - We Gotta Go Now\26_tel.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\05 - We Gotta Go Now\27_Thai.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\05 - We Gotta Go Now\28_Chinese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\05 - We Gotta Go Now\29_Chinese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\05 - We Gotta Go Now\2_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\05 - We Gotta Go Now\30_Japanese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\05 - We Gotta Go Now\31_Korean.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\05 - We Gotta Go Now\3_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\05 - We Gotta Go Now\4_may.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\05 - We Gotta Go Now\5_Danish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\05 - We Gotta Go Now\6_German.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\05 - We Gotta Go Now\7_Spanish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\05 - We Gotta Go Now\8_Spanish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\05 - We Gotta Go Now\9_fil.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\06 - The Bloody Doors Off\10_French.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\06 - The Bloody Doors Off\11_Hebrew.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\06 - The Bloody Doors Off\12_hin.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\06 - The Bloody Doors Off\13_Indonesian.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\06 - The Bloody Doors Off\14_Italian.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\06 - The Bloody Doors Off\15_Japanese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\06 - The Bloody Doors Off\16_Korean.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\06 - The Bloody Doors Off\17_may.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\06 - The Bloody Doors Off\18_Bokmal.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\06 - The Bloody Doors Off\19_Dutch.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\06 - The Bloody Doors Off\20_Polish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\06 - The Bloody Doors Off\21_Portuguese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\06 - The Bloody Doors Off\22_Portuguese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\06 - The Bloody Doors Off\23_Russian.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\06 - The Bloody Doors Off\24_Swedish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\06 - The Bloody Doors Off\25_tam.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\06 - The Bloody Doors Off\26_tel.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\06 - The Bloody Doors Off\27_Thai.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\06 - The Bloody Doors Off\28_Turkish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\06 - The Bloody Doors Off\29_Chinese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\06 - The Bloody Doors Off\2_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\06 - The Bloody Doors Off\30_Chinese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\06 - The Bloody Doors Off\3_Arabic.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\06 - The Bloody Doors Off\4_Danish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\06 - The Bloody Doors Off\5_German.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\06 - The Bloody Doors Off\6_Spanish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\06 - The Bloody Doors Off\7_Spanish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\06 - The Bloody Doors Off\8_Finnish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\06 - The Bloody Doors Off\9_fil.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\07 - Butcher, Baker, Candlestick Maker\10_French.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\07 - Butcher, Baker, Candlestick Maker\11_Hebrew.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\07 - Butcher, Baker, Candlestick Maker\12_hin.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\07 - Butcher, Baker, Candlestick Maker\13_Indonesian.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\07 - Butcher, Baker, Candlestick Maker\14_Italian.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\07 - Butcher, Baker, Candlestick Maker\15_Japanese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\07 - Butcher, Baker, Candlestick Maker\16_Korean.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\07 - Butcher, Baker, Candlestick Maker\17_may.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\07 - Butcher, Baker, Candlestick Maker\18_Bokmal.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\07 - Butcher, Baker, Candlestick Maker\19_Dutch.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\07 - Butcher, Baker, Candlestick Maker\20_Polish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\07 - Butcher, Baker, Candlestick Maker\21_Portuguese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\07 - Butcher, Baker, Candlestick Maker\22_Portuguese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\07 - Butcher, Baker, Candlestick Maker\23_Russian.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\07 - Butcher, Baker, Candlestick Maker\24_Swedish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\07 - Butcher, Baker, Candlestick Maker\25_tam.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\07 - Butcher, Baker, Candlestick Maker\26_tel.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\07 - Butcher, Baker, Candlestick Maker\27_Thai.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\07 - Butcher, Baker, Candlestick Maker\28_Turkish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\07 - Butcher, Baker, Candlestick Maker\29_Chinese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\07 - Butcher, Baker, Candlestick Maker\2_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\07 - Butcher, Baker, Candlestick Maker\30_Chinese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\07 - Butcher, Baker, Candlestick Maker\3_Arabic.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\07 - Butcher, Baker, Candlestick Maker\4_Danish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\07 - Butcher, Baker, Candlestick Maker\5_German.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\07 - Butcher, Baker, Candlestick Maker\6_Spanish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\07 - Butcher, Baker, Candlestick Maker\7_Spanish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\07 - Butcher, Baker, Candlestick Maker\8_Finnish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\07 - Butcher, Baker, Candlestick Maker\9_fil.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\08 - What I Know\10_fil.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\08 - What I Know\11_French.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\08 - What I Know\12_Hebrew.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\08 - What I Know\13_hin.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\08 - What I Know\14_Indonesian.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\08 - What I Know\15_Italian.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\08 - What I Know\16_Japanese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\08 - What I Know\17_Korean.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\08 - What I Know\18_may.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\08 - What I Know\19_nor.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\08 - What I Know\20_Dutch.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\08 - What I Know\21_Polish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\08 - What I Know\22_Portuguese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\08 - What I Know\23_Portuguese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\08 - What I Know\24_Russian.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\08 - What I Know\25_Swedish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\08 - What I Know\26_tam.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\08 - What I Know\27_tel.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\08 - What I Know\28_Thai.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\08 - What I Know\29_Turkish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\08 - What I Know\2_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\08 - What I Know\30_Chinese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\08 - What I Know\31_Chinese.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\08 - What I Know\3_Arabic.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\08 - What I Know\4_Danish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\08 - What I Know\5_German.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\08 - What I Know\6_English.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\08 - What I Know\7_Spanish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\08 - What I Know\8_Spanish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Boys\Season 2\Subs\08 - What I Know\9_Finnish.srt",
		@"F:\_TorrentCache\_Completed (local)\TV\The Orville\Season 2\01 - Jaloja.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\The Orville\Season 2\02 - Primal Urges.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\The Orville\Season 2\03 - Home.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\The Orville\Season 2\04 - Nothing Left On Earth Excepting Fishes.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\The Orville\Season 2\05 - All The World Is Birthday Cake.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\The Orville\Season 2\06 - A Happy Refrain.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\The Orville\Season 2\07 - Deflectors.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\The Orville\Season 2\08 - Identity (Part 1).mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\The Orville\Season 2\09 - Identity (Part 2).mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\The Orville\Season 2\10 - Blood Of Patriots.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\The Orville\Season 2\11 - Lasting Impressions.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\The Orville\Season 2\12 - Sanctuary.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\The Orville\Season 2\13 - Tomorrow, And Tomorrow, And Tomorrow.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\The Orville\Season 2\14 - The Road Not Taken.mkv",
		@"F:\_TorrentCache\_Completed (local)\TV\Wu-Tang Clan - Of Mics and Men\Season 1\01 - Episode 1.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Wu-Tang Clan - Of Mics and Men\Season 1\02 - Episode 2.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Wu-Tang Clan - Of Mics and Men\Season 1\03 - Episode 3.mp4",
		@"F:\_TorrentCache\_Completed (local)\TV\Wu-Tang Clan - Of Mics and Men\Season 1\04 - Episode 4.mp4"
				});
			#endregion

            var directories = vfs.Directory.GetDirectories("F:");

		}

	}
}
